{{- if .Values.balanceApi.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.balanceApi.serviceAccount.name }}
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: balance-api
  annotations:
    {{- toYaml .Values.balanceApi.serviceAccount.annotations | nindent 4 }}
{{- end }}
