{{- if .Values.balanceUi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "volleyball-bot.fullname" . }}-balance-ui
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: balance-ui
spec:
  type: {{ .Values.balanceUi.service.type }}
  ports:
    - port: {{ .Values.balanceUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "volleyball-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: balance-ui
{{- end }}
