{{- if and .Values.balanceApi.enabled .Values.balanceApi.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "volleyball-bot.fullname" . }}-balance-api
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: balance-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "volleyball-bot.fullname" . }}-balance-api
  minReplicas: {{ .Values.balanceApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.balanceApi.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.balanceApi.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
