{{- if .Values.balanceApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "volleyball-bot.fullname" . }}-balance-api
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: balance-api
spec:
  type: {{ .Values.balanceApi.service.type }}
  ports:
    - port: {{ .Values.balanceApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "volleyball-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: balance-api
{{- end }}
