{{- if .Values.botApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "volleyball-bot.fullname" . }}-bot-api
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot-api
spec:
  type: {{ .Values.botApi.service.type }}
  ports:
  - port: {{ .Values.botApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "volleyball-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot-api
{{- end }}
