{{- if .Values.botApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.botApi.serviceAccount.name }}
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot-api
  {{- with .Values.botApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.jobs.triviaTuesday.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobs.triviaTuesday.serviceAccount.name }}
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: trivia-job
  {{- with .Values.jobs.triviaTuesday.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.jobs.gamePollTuesday.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobs.gamePollTuesday.serviceAccount.name }}
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: game-poll-job
  {{- with .Values.jobs.gamePollTuesday.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.jobs.notificationMonday.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobs.notificationMonday.serviceAccount.name }}
  labels:
    {{- include "volleyball-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-job
  {{- with .Values.jobs.notificationMonday.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
